### ISSUE TITLE
TightConstraintSet not working with Signomials

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#608]
```python
from gpkit import Variable, Model
from gpkit.constraints.tight import TightConstraintSet as TCS
from gpkit import LinkedConstraintSet

x = Variable('x'); y = Variable('y');
m = Model(x, [TCS([x >= y]), x >= 2, y >= 1])
m.solve()
# returns error as you would expect

m1 = Model(x, [TCS([x >= y]), x >= 2])
m2 = Model(y, [y>=1])
lc = LinkedConstraintSet([m1, m2])
m3 = Model(m1['x'], lc)
m3.solve()
# doesn't return an error #whoops
```

**Comment by pgkirsch** [comment]
For what it's worth, this was working at commit 846d454, but something in the commits since then have broken it.

**Comment by bqpd** [comment]
Fixed in #605

**Comment by bqpd** [comment]
Fixed in #605

**Comment by pgkirsch** [comment]
Hmm when I pull `fixtight`, it still doesn't appear to be working using `vtail`, which links with wing box....

**Comment by pgkirsch** [comment]
This issue is important for thesis research - fixing it would be a huge help!

**Comment by whoburg** [comment]
clarification: to replicate this: check out the `fixtight` branch of gpkit, edit `constraints/tight.py` to add a print statement to `process_result`, and run the `vtail.py` on the current master branch of gpkit-models. The print statement will not get executed.

**Comment by whoburg** [comment]
updated MWE to reproduce this issue below. `fixtight` branch does not currently resolve.

```python
from gpkit import Variable, Model
from gpkit.constraints.tight import TightConstraintSet as TCS
from gpkit import LinkedConstraintSet, SignomialsEnabled

x = Variable('x'); y = Variable('y');
# m = Model(x, [TCS([x >= y]), x >= 2, y >= 1])
# m.solve()  # commented to avoid throwing error here
# returns error as you would expect

with SignomialsEnabled():
    sig_constraint = (x + y >= 0.1)
m1 = Model(x, [TCS([x >= y]), x >= 2])
m2 = Model(y, [y>=1, sig_constraint])
lc = LinkedConstraintSet([m1, m2])
m3 = Model(m1['x'], lc)
m3.localsolve()
# doesn't return an error #whoops
```

**Comment by whoburg** [comment]
This has nothing to do with composed models -- it has to do with Signomials

even simpler MWE
```python
from gpkit import Variable, Model, SignomialsEnabled
from gpkit.constraints.tight import TightConstraintSet as TCS

x = Variable('x')
y = Variable('y')
with SignomialsEnabled():
    sig_constraint = (x + y >= 0.1)
m1 = Model(x, [TCS([x >= y]), x >= 2, y >= 1, sig_constraint])
m1.localsolve()
# doesn't return an error #whoops
```

**Comment by bqpd** [comment]
Fixed in #605 now, and test added.
