### ISSUE TITLE
numpy bools showing up as constraints in tests

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#794]
you can see them by uncommenting this line https://github.com/hoburg/gpkit/pull/787/files/0f425f6e3ba7a2bf56b596de7ca9452334bb1947#diff-239d6c98c4984f5dd74cfd8222ed2d3dR140

**Comment by bqpd** [comment]
They're from nomialarray == constraints

**Comment by whoburg** [comment]
the line to uncomment link is broken; what's the actual resolution on this? Do we think the issue is fixed?

**Comment by bqpd** [comment]
It's not fixed, but it happens for a reason (nomialarray's ==). I created the issue when I didn't know why they were there.

**Comment by whoburg** [comment]
what specifically is the limitation on using == when one or more side is a NomialArray?

Can I make the constraint x == y where x and/or y are VectorVariables?
How about x**2 == y**3?

**Comment by bqpd** [comment]
```python
In [1]: from gpkit import *

In [2]: x = VectorVariable(2, "x")

In [3]: y = VectorVariable(2, "y")

In [4]: z = Variable("z")

In [5]: z == x
Out[5]: gpkit.ArrayConstraint(x = z)

In [6]: x == y
Out[6]: gpkit.ArrayConstraint(x = y)

In [7]: y == z
Out[7]: gpkit.ArrayConstraint(y = z)

In [8]: (y == z).as_posyslt1()
Out[8]: 
[gpkit.Monomial(y_(0,)*z**-1),
 gpkit.Monomial(y_(0,)**-1*z),
 gpkit.Monomial(y_(1,)*z**-1),
 gpkit.Monomial(y_(1,)**-1*z)]

```

**Comment by whoburg** [comment]
... so what causes the numpy bools, and are they a problem? (I'm responding to your "it's not fixed" above).

**Comment by bqpd** [comment]
Ah. They occur when you use `==` to check equality with a nomialarray.

**Comment by bqpd** [comment]
I think? Hmm, I think attempts to do so just error, now...
